spring:
  application:
    name: Sample
  mvc:
    static-path-pattern: /static/**
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: ENC(yUdyguqidS7FSIPtvviK28nW+sA8kzHkMQFTvOy/8Pikt8m/HDjbrpfgvpWjZb0sJI0MCEY19Psx0SGWY57NXSkYLbxs0/IyqWxDZ3jNPJJ5pdUn86UphzcmQ/zS7iBoO878LMYGumHh7pzHAYUPD+9XJ5FkTAHo)
#    username: ENC(3HtdKdvb8e4lkFRt2TEzSs5WnIGk4C9K)
#    password: ENC(ABPuh3mrBhg/R4uNz3i2Po3h99Jl6mXr)
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://jadefromkorea.synology.me:54320/postgres
    username: postgres
    password: 123456
##    url: jdbc:postgresql://jadefromkorea.synology.me:54320/postgres
    hikari:
      connection-timeout: 20000
      minimum-idle: 20
      maximum-pool-size: 40
      idle-timeout: 1000
      max-lifetime: 1000000
#  thymeleaf:
#    cache: false
#    prefix: classpath:templates/
#    suffix: .html
#    check-template-location: true

#  # thymeleaf 사용 여부
#  spring.thymeleaf.enabled=true
#  # template 경로 접두사
#  spring.thymeleaf.prefix=classpath:/templates/
#  # template 경로 접미사
#  spring.thymeleaf.suffix=.html
#  # cache 활성화 여부, 개발환경에서는 비 활성화
#  spring.thymeleaf.cache=true;
#  # template 인코딩
#  spring.thymeleaf.encoding=UTF-8
#  #기본 template 모드, TemplateMode에 정의 (HTML, XML, TEXT, JAVASCRIPT 등)
#  spring.thymeleaf.mode=HTML
#  # 렌더링 전에 template 존재 여부 확인
#  spring.thymeleaf.check-template=true
#  # template 위치 존재 여부 확인
#  spring.thymeleaf.check-template-location=true

  thymeleaf:
    # thymeleaf 사용 여부
    enabled: true
    # template 경로 접두사
    prefix: classpath:templates/
    # template 경로 접미사
    suffix: .html
    # cache 활성화 여부, 개발환경에서는 비 활성화
    cache: false
    # template 인코딩
    encoding: UTF-8
    #기본 template 모드, TemplateMode에 정의 (HTML, XML, TEXT, JAVASCRIPT 등)
    mode: HTML
    # 렌더링 전에 template 존재 여부 확인
    check-template: true
    # template 위치 존재 여부 확인
    check-template-location: true

#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200MB
#      max-request-size: 215MB
#  jackson:
#    time-zone: Asia/Seoul
#  thymeleaf:
#    check-template-location: true
#    prefix: webapp/WEB-INF/views
#    suffix: .html
#    mode: LEGACYHTML5
#    encoding: utf-8
#    servlet:
#      content-type: text/html
#    cache: false
#    template-resolver-order: 0
#  web:
#    resources:
#      static-locations: classpath:/static/
#      add-mappings: true
mybatis:
  #  mapper 파일 경로 지정. 아래 형식은 mapper 디렉토리 하위의 모든 xml 파일을 포함.
  mapper-locations: mapper/**/*.xml
  # @Alias를 스캔하는 경로 설정. 아래 형식은 프로젝트의 전체를 스캔.
  type-aliases-package: com.example.samplemybatis
  configuration:
    # db 컬럼명에서 언더바를 제거한 후 카멜케이스로 변경하여 리턴.
    map-underscore-to-camel-case: true
server:
  port: 9090
logging:
  level:
    root: info